# Generated by Django 6.1.1 on 2026-10-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0003_alter_barbero_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
    ]
