# Generated by Django 6.1.1 on 2026-10-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0004_barbero_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_creacion',
        ),
    ]
