# Generated by Django 6.1.1 on 2026-10-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0005_remove_cita_fecha_creacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='barbero',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barbero',
            name='nota_pausa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cita',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barbero',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='barberos', to='barberia.servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='barberia.servicio'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha_hora_inicio'], name='cita_estado_fecha_idx'),
        ),
    ]
