# Generated by Django 6.1.1 on 2026-10-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0006_servicio_barbero_activo_barbero_nota_pausa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='despedido',
            field=models.BooleanField(default=False),
        ),
    ]
