# Generated by Django 6.1.1 on 2026-10-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0007_barbero_despedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
