# Generated by Django 6.1.1 on 2026-10-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_apellido_user_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant_id',
        ),
    ]
