# Generated by Django 6.1.1 on 2026-10-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_activo_remove_user_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BARBERO', 'Barbero'), ('CLIENTE', 'Cliente'), ('Dueño', 'Dueño')], default='CLIENTE', max_length=20),
        ),
    ]
